name: ci
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: ["1.14", "1.15"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: |
          go test -cover -coverprofile coverage.txt -race -v ./...
      - uses: codecov/codecov-action@v1
