title: Kythe
url: 'https://kythe.io'
description: >
  A pluggable, (mostly) language-agnostic ecosystem for building tools that work
  with code.
permalink: pretty
future: false
exclude: ['README.adoc', 'Gemfile.lock', 'Gemfile', 'build.sh', 'check_links_test.sh', 'site_docs.bzl', 'BUILD', 'doc_header.rb']
collections:
  docs:
    output: true
    permalink: /:collection/:path:output_ext
plugins:
  - jekyll-redirect-from
  - jekyll-asciidoc
asciidoctor:
  attributes:
    - hardbreaks!
    - source-highlighter=pygments
sass:
  # Paths are CWD relative, not --source relative.
  # https://github.com/jekyll/jekyll-sass-converter/issues/115
  sourcemap: never
