name: Tests

on:
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      GOFLAGS: -mod=vendor
      GOPROXY: "off"

    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Format
      run: make fmt

    - name: Vet
      run: make vet

    - name: Lint
      run: |
        make install-lint
        make lint

    - name: Staticcheck
      run: |
        make install-staticcheck
        make staticcheck

    - name: Test
      run: make test
